const responses = {
    yes: [
        "Absolutely",
        "Indeed",
        "Sure thing",
        "Affirmative",
        "Without a doubt",
        "Of course",
        "Definitely",
        "You bet",
        "Absolutely",
        "By all means",
        "Certainly",
        "Sure",
        "Yup",
        "Absolutely",
        "Okay",
        "Agreed",
        "Very well",
        "All right",
        "Naturally",
        "No problem",
        "No doubt",
        "Positively",
        "Indubitably",
        "Undoubtedly",
        "Most certainly",
        "Yep",
        "Absolutely",
        "Without question",
        "Of course, I will",
        "Affirmative, I'm in",
        "That's a go",
        "Absolutely, I'm on board",
        "Yes, I agree",
        "I'm all for it",
        "Sure, why not?",
        "You got it",
        "That works for me",
        "Count me in",
        "You can count on me",
        "Absolutely, I'm with you",
        "I'm in complete agreement",
        "That's a definite yes",
        "I couldn't agree more",
        "Without hesitation",
        "No objections here",
        "I'm absolutely on your side",
        "That's a resounding yes",
        "Undeniably",
        "Certainly, no problem",
        "I wholeheartedly say yes",
        "Affirmatively speaking",
        "Without any reservations",
        "I concur",
        "For sure",
        "Without fail",
        "Gladly",
        "Positively, without a doubt",
        "I'm absolutely positive",
        "Most assuredly",
        "Definitely, I'm in favor",
        "Without a shadow of a doubt",
        "Very much so",
        "Without wavering",
        "I'll gladly do that",
        "Certainly, with pleasure",
        "I endorse that wholeheartedly",
        "Unquestionably",
        "That's an emphatic yes",
        "Undoubtedly, yes",
        "Affirmative, I support that",
        "That's my sentiment exactly",
        "Without question or doubt",
        "I'm completely on board",
        "I'm all in",
        "Without any second thoughts",
        "Absolutely, no doubt about it",
        "Without a moment's hesitation",
        "Sure, I'm game",
        "That's a definite thumbs up",
        "Absolutely, I'm excited",
        "I'm completely convinced",
        "Yes, I'm 100% behind you",
        "No ifs, ands, or buts",
        "Without any qualms",
        "I agree wholeheartedly",
        "I'm positively inclined",
        "Most certainly, count me in",
        "Absolutely, I'm eager",
        "I'm on your side without question",
        "That's an unequivocal yes",
        "Certainly, I'm ready",
        "That's an absolute yes",
        "I'm fully supportive",
        "Without any hesitation whatsoever",
        "Absolutely, I'm enthusiastic",
        "I'm without a doubt in agreement",
        "That's a positive yes",
        "Without any debate",
        "I'm without reservation",
        "Wholeheartedly, yes"
    ],
    no: [
        "No",
        "Nope",
        "Not at all",
        "Negative",
        "Sorry, but no",
        "Absolutely not",
        "No way",
        "Certainly not",
        "I'm afraid not",
        "I can't",
        "I'm sorry, but no",
        "I don't think so",
        "No chance",
        "I respectfully decline",
        "That's a firm no",
        "Regrettably, no",
        "No way in hell",
        "Not a chance",
        "I'm not able to",
        "No, thank you",
        "No, I can't do that",
        "Not for me",
        "I'm not interested",
        "No, I'm not available",
        "I'm unable to comply",
        "No, that won't work for me",
        "I'm really sorry, but no",
        "I'm not up for it",
        "I'd rather not",
        "I'm saying no",
        "No, I'm not willing to do that",
        "I'm not inclined to agree",
        "No, I'm not in favor of it",
        "I have to decline",
        "No, I don't want to",
        "That's not possible",
        "No, that's not what I'm looking for",
        "I can't say yes to that",
        "No, I'm not on board",
        "I'm sorry, but that's a no",
        "I have to say no",
        "No, I'm not supportive of it",
        "I'm not prepared to do that",
        "I'm sorry, but I have to refuse",
        "No, that's against my principles",
        "That's not within my capabilities",
        "No, that doesn't work for me",
        "I'm not able to accommodate that",
        "No, I'm not willing to compromise",
        "I can't give you a positive answer",
        "I have to reject that idea",
        "No, I'm not convinced",
        "I'm not open to that suggestion",
        "No, I don't see it happening",
        "I'm sorry, but I can't agree to that",
        "No, that's not acceptable to me",
        "I can't make that happen",
        "I'm not ready for that",
        "No, that's not what I had in mind",
        "I can't support that decision",
        "I'm sorry, but that's out of the question",
        "No, I can't be part of it",
        "I'm not able to fulfill that request",
        "No, I'm not interested in participating",
        "I can't go along with that",
        "No, I'm not convinced of its value",
        "I'm sorry, but that's not an option",
        "No, I don't believe that's the right choice",
        "I can't endorse that idea",
        "No, I don't think that's feasible",
        "I'm not willing to make that commitment",
        "No, that's not what I had agreed to",
        "I can't see myself doing that",
        "No, that's not what I had anticipated",
        "I'm sorry, but I can't support that",
        "No, I don't see the benefits of it",
        "I can't align myself with that decision",
        "No, I don't think that's a good idea",
        "I'm not comfortable with that proposition",
        "No, I can't get on board with that"
    ],
    itsPossible: [
        "There's a chance",
        "It could happen",
        "It's within the realm of possibility",
        "It's a viable option",
        "It's conceivable",
        "It's a potential outcome",
        "It's not out of the question",
        "It's on the table",
        "It's a realistic possibility",
        "It's within the realm of feasibility",
        "It's a plausible scenario",
        "It's a likely prospect",
        "It's within the realm of likelihood",
        "It's a feasible option",
        "It has a possibility of occurring",
        "It's a realistic chance",
        "It's an attainable goal",
        "It's a viable alternative",
        "It's not improbable",
        "It has the potential to happen",
        "It's a reachable outcome",
        "It's not far-fetched",
        "It's a credible possibility",
        "It's not beyond the realm of possibility",
        "It's a possible course of action",
        "It's an achievable objective",
        "It's not entirely unlikely",
        "It's a feasible solution",
        "It's a conceivable result",
        "It's not an impossible notion",
        "It's a reasonable chance",
        "It has a fair shot",
        "It's not an outlandish idea",
        "It's a possible direction",
        "It's a potential path",
        "It's not without possibility",
        "It's a reachable target",
        "It's a practical option",
        "It's not without a chance"
    ]
  };
  
  let currentResponse = null;
  
  function getRandomType() {
    const types = Object.keys(responses);
    const randomIndex = Math.floor(Math.random() * types.length);
    return types[randomIndex];
  }
  
  function getRandomResponse(type) {
    const array = responses[type];
    const randomIndex = Math.floor(Math.random() * array.length);
    return array[randomIndex];
  }
  
  function randomizeResponse() {
    if (!currentResponse) {
      const randomType = getRandomType();
      currentResponse = getRandomResponse(randomType);
      document.getElementById("response").textContent = currentResponse;
      document.getElementById("randomizeButton").classList.add("hide");
      document.getElementById("resetButton").classList.remove("hide");
    }
  }
  
  function resetResponse() {
    currentResponse = null;
    document.getElementById("response").textContent = "";
    document.getElementById("randomizeButton").classList.remove("hide");
    document.getElementById("resetButton").classList.add("hide");
  }
  
  document.getElementById("randomizeButton").addEventListener("click", randomizeResponse);
  document.getElementById("resetButton").addEventListener("click", resetResponse);
  
  // Initially hide the reset button
  document.getElementById("resetButton").classList.add("hide");
  